spring:
  datasource:
    url: jdbc:postgresql://90.189.153.65:5433/postgres?currentSchema=public
    username: postgres
    password: user
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true